Update block_sites script
- Read sites to block from file
- Fix shebang
- Remove unblock functionality to make it more slightly more tedious to undo

diff --git a/scripts/bin/block_sites b/scripts/bin/block_sites
--- a/scripts/bin/block_sites
+++ b/scripts/bin/block_sites
@@ -1,38 +1,34 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# * Helpers
+basedir=$(dirname "$(realpath "$0")")
 
-if [[ $EUID -ne 0 ]]; then
-  echo "Must run as root."
-  exit 1
-fi
-
-block_sites="www.reddit.com wololo.net www.last.fm bbs.archlinux.org www.tumblr.com twitter.com www.youtube.com"
-
-unblock_sites() {
-	echo "unblocking sites"
-	mv /etc/hosts.bak /etc/hosts
+error() {
+    echo "$@" >&2
+    exit 1
 }
 
-block_sites() {
+block_sites() {  # block_file
+	block_file=$1
+
 	if [[ ! -f /etc/hosts.bak ]]; then
-		cp /etc/hosts /etc/hosts.bak || (echo "Error backing up /etc/hosts. Exiting." ; exit 1)
+		cp /etc/hosts /etc/hosts.bak \
+			|| error "Error backing up /etc/hosts. Exiting."
 	fi
-	for site in $block_sites; do
-		echo "blocking $site"
-		echo "0.0.0.0 $site" >> /etc/hosts
-	done
+
+	while read -r entry; do
+		if [[ -z $entry ]] || [[ $entry =~ \# ]]; then
+			continue
+		fi
+		echo "blocking $entry"
+		echo "0.0.0.0 $entry" >> /etc/hosts
+	done < "$block_file"
 }
 
-if [[ -n $1 ]]; then
-	if [[ $1 == block ]]; then
-		block_sites
-	elif [[ $1 == unblock ]]; then
-		unblock_sites
-	fi
-else
-	if [[ -f /etc/hosts.bak ]]; then
-		unblock_sites
-	else
-		block_sites
-	fi
+# * Main
+if [[ $EUID -ne 0 ]]; then
+  error "Must run as root."
 fi
 
+ruleset=${1:-default}
+block_file="$basedir"/block_sites_"$ruleset".txt
+block_sites "$block_file"
